// ek_-Migrations-SQL als Teil des Contracts: Single Source of Truth für
// CLI (schreibt supabase/migrations-Dateien) und Studio (spielt die SQL
// über die Supabase-Management-API ein).

/** Default-Locale der i18n-/Collections-Migration — identisch zum CLI-Default. */
const DEFAULT_LOCALE = "de";

/**
 * SQL migration for the customer's Supabase. Tables use the `ek_` prefix.
 *
 * RLS principle: anon/authenticated can read ONLY published content
 * (joined via published_version_id). All writes and draft reads go through
 * service_role (used server-side by the Studio and Draft Mode) —
 * service_role bypasses RLS, so it gets no policies of its own.
 *
 * Idempotent: `if not exists`, `drop policy if exists`, `on conflict do nothing`.
 */
export function initMigration(): string {
  return `-- Editkraft: content tables in the customer project (prefix ek_).
-- Generated by: editkraft init

-- Status enum (idempotent)
do $$
begin
  if not exists (select 1 from pg_type where typname = 'ek_page_status') then
    create type public.ek_page_status as enum ('draft', 'published');
  end if;
end $$;

-- updated_at trigger function
create or replace function public.ek_set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

-- ---------------------------------------------------------------------------
-- ek_pages
-- ---------------------------------------------------------------------------
create table if not exists public.ek_pages (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  title text not null,
  meta jsonb not null default '{}'::jsonb,
  status public.ek_page_status not null default 'draft',
  published_version_id uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists ek_pages_set_updated_at on public.ek_pages;
create trigger ek_pages_set_updated_at before update on public.ek_pages
  for each row execute function public.ek_set_updated_at();

-- ---------------------------------------------------------------------------
-- ek_page_versions (append-only; every save is a new version)
-- ---------------------------------------------------------------------------
create table if not exists public.ek_page_versions (
  id uuid primary key default gen_random_uuid(),
  page_id uuid not null references public.ek_pages (id) on delete cascade,
  content jsonb not null,
  schema_version text not null,
  created_by uuid,
  created_at timestamptz not null default now()
);

create index if not exists ek_page_versions_page_id_idx
  on public.ek_page_versions (page_id);

-- FK can only be set after ek_page_versions exists (published_version_id -> version)
do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'ek_pages_published_version_fk'
  ) then
    alter table public.ek_pages
      add constraint ek_pages_published_version_fk
      foreign key (published_version_id)
      references public.ek_page_versions (id) on delete set null;
  end if;
end $$;

-- ---------------------------------------------------------------------------
-- ek_assets
-- ---------------------------------------------------------------------------
create table if not exists public.ek_assets (
  id uuid primary key default gen_random_uuid(),
  storage_path text not null,
  alt text,
  width int,
  height int,
  mime_type text not null,
  created_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- Storage bucket for assets (public: published images are public)
-- ---------------------------------------------------------------------------
insert into storage.buckets (id, name, public)
values ('ek-assets', 'ek-assets', true)
on conflict (id) do nothing;

-- ---------------------------------------------------------------------------
-- RLS: anon/authenticated can read ONLY published content.
-- Writes & draft reads go through service_role (bypasses RLS).
-- ---------------------------------------------------------------------------
alter table public.ek_pages enable row level security;
alter table public.ek_page_versions enable row level security;
alter table public.ek_assets enable row level security;

grant select on public.ek_pages to anon, authenticated;
grant select on public.ek_page_versions to anon, authenticated;
grant select on public.ek_assets to anon, authenticated;

-- service_role: full access (Studio & Draft Mode write server-side).
-- service_role also bypasses RLS (BYPASSRLS).
grant all on public.ek_pages to service_role;
grant all on public.ek_page_versions to service_role;
grant all on public.ek_assets to service_role;

drop policy if exists "ek public reads published pages" on public.ek_pages;
create policy "ek public reads published pages"
  on public.ek_pages for select
  to anon, authenticated
  using (status = 'published' and published_version_id is not null);

drop policy if exists "ek public reads published versions" on public.ek_page_versions;
create policy "ek public reads published versions"
  on public.ek_page_versions for select
  to anon, authenticated
  using (
    id in (
      select published_version_id from public.ek_pages
      where status = 'published' and published_version_id is not null
    )
  );

drop policy if exists "ek public reads assets" on public.ek_assets;
create policy "ek public reads assets"
  on public.ek_assets for select
  to anon, authenticated
  using (true);
`;
}

/**
 * i18n contract migration (Roadmap 1.4): adds `locale` + `translation_group_id`
 * to `ek_pages` and replaces the `unique(slug)` constraint with
 * `unique(slug, locale)`. Ships as a SECOND, separate migration so existing
 * installations can apply it independently of the init migration.
 *
 * Additive and idempotent: `if not exists` / `drop constraint if exists` guards,
 * safe to run on existing installations and safe to re-run.
 */
export function i18nMigration(defaultLocale: string): string {
  if (!/^[A-Za-z0-9-]+$/.test(defaultLocale)) {
    throw new Error(
      `Invalid defaultLocale "${defaultLocale}": must match /^[A-Za-z0-9-]+$/ (it is interpolated into SQL).`,
    );
  }
  return `-- Editkraft i18n contract (Roadmap 1.4): locale + translation groups.
-- Additive; safe to run on existing installations.

alter table public.ek_pages
  add column if not exists locale text not null default '${defaultLocale}';

alter table public.ek_pages
  add column if not exists translation_group_id uuid not null default gen_random_uuid();

-- Replace unique(slug) with unique(slug, locale).
-- 'ek_pages_slug_key' is the implicit constraint name from \`slug text not null unique\`.
alter table public.ek_pages drop constraint if exists ek_pages_slug_key;

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'ek_pages_slug_locale_key'
  ) then
    alter table public.ek_pages
      add constraint ek_pages_slug_locale_key unique (slug, locale);
  end if;
end $$;

create index if not exists ek_pages_translation_group_idx
  on public.ek_pages (translation_group_id);
`;
}

/**
 * Dritte Migration: Site-Globals (`ek_globals`). Additiv und idempotent —
 * Bestandsinstallationen holen sie unabhängig von init/i18n nach.
 *
 * Sicherheitsmodell (ADR-009-Prinzip): Der Draft darf NIE öffentlich lesbar
 * sein. RLS filtert nur Zeilen, keine Spalten — deshalb zusätzlich ein
 * Spalten-GRANT: anon/authenticated sehen nur id/published/updated_at.
 * Supabase-Default-Privileges werden vorher explizit zurückgenommen.
 */
export function globalsMigration(): string {
  return `-- Editkraft Site-Globals: eine Zeile pro Site, draft/published getrennt.
-- Additive; safe to run on existing installations.

create table if not exists public.ek_globals (
  id smallint primary key default 1 check (id = 1),
  draft jsonb,
  published jsonb,
  updated_at timestamptz not null default now()
);

drop trigger if exists ek_globals_set_updated_at on public.ek_globals;
create trigger ek_globals_set_updated_at before update on public.ek_globals
  for each row execute function public.ek_set_updated_at();

alter table public.ek_globals enable row level security;

-- Draft nie öffentlich: Spalten-GRANT statt Zeilen-Policy allein.
revoke all on public.ek_globals from anon, authenticated;
grant select (id, published, updated_at) on public.ek_globals to anon, authenticated;
grant all on public.ek_globals to service_role;

drop policy if exists "ek public reads published globals" on public.ek_globals;
create policy "ek public reads published globals"
  on public.ek_globals for select
  to anon, authenticated
  using (published is not null);

insert into public.ek_globals (id) values (1) on conflict (id) do nothing;
`;
}

/**
 * Vierte Migration: reservierte Symbols-Tabelle (`ek_symbols`, Roadmap 2.4).
 * Additiv und idempotent; in v1 ungenutzt und ohne öffentlichen Zugriff.
 */
export function symbolsMigration(): string {
  return `-- Editkraft Symbols (reserviert für V2, Roadmap 2.4): wiederverwendbare Blöcke.
-- Additive; safe to run on existing installations. In v1 ungenutzt —
-- der Renderer wirft für $symbol-Knoten SYMBOLS_UNSUPPORTED.

create table if not exists public.ek_symbols (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  content jsonb not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists ek_symbols_set_updated_at on public.ek_symbols;
create trigger ek_symbols_set_updated_at before update on public.ek_symbols
  for each row execute function public.ek_set_updated_at();

alter table public.ek_symbols enable row level security;

-- V1: kein öffentlicher Zugriff (keine Policies für anon/authenticated);
-- Schreiben/Lesen nur Service-Role. Die Published-Lese-Policy kommt mit V2.
revoke all on public.ek_symbols from anon, authenticated;
grant all on public.ek_symbols to service_role;
`;
}

/**
 * Collections migration (Roadmap 2.8): `ek_collections` + `ek_collection_items`
 * for structured, repeatable content (blog posts, …). Ships as a separate
 * migration so existing installations can apply it independently.
 *
 * Draft/publish is a SNAPSHOT model (`published_data`), not a version log:
 * anon sees only rows whose `published_data is not null` — the policy exposes
 * exactly the published view. All writes go through service_role (bypasses RLS).
 *
 * Additive and idempotent: `if not exists` / `drop policy if exists` guards,
 * safe to run on existing installations and safe to re-run.
 */
export function collectionsMigration(defaultLocale: string): string {
  if (!/^[A-Za-z0-9-]+$/.test(defaultLocale)) {
    throw new Error(
      `Invalid defaultLocale "${defaultLocale}": must match /^[A-Za-z0-9-]+$/ (it is interpolated into SQL).`,
    );
  }
  return `-- Editkraft collections (Roadmap 2.8): structured item lists (blog, …).
-- Additive; safe to run on existing installations.

-- ---------------------------------------------------------------------------
-- ek_collections (collection definitions; the schema is not a secret)
-- ---------------------------------------------------------------------------
create table if not exists public.ek_collections (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  name text not null,
  item_schema jsonb not null,
  created_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- ek_collection_items (draft/publish as snapshot: published_data;
-- null = never published — no per-item version log in v1)
-- ---------------------------------------------------------------------------
create table if not exists public.ek_collection_items (
  id uuid primary key default gen_random_uuid(),
  collection_id uuid not null references public.ek_collections (id) on delete cascade,
  slug text not null,
  locale text not null default '${defaultLocale}',
  translation_group_id uuid not null default gen_random_uuid(),
  draft_data jsonb not null,
  published_data jsonb,
  published_at timestamptz,
  sort_order integer,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (collection_id, slug, locale)
);

create index if not exists ek_collection_items_collection_id_idx
  on public.ek_collection_items (collection_id);

create index if not exists ek_collection_items_translation_group_idx
  on public.ek_collection_items (translation_group_id);

-- updated_at trigger, same mechanism as ek_pages (ek_set_updated_at is
-- created by the init migration, which always applies before this one).
drop trigger if exists ek_collection_items_set_updated_at on public.ek_collection_items;
create trigger ek_collection_items_set_updated_at before update on public.ek_collection_items
  for each row execute function public.ek_set_updated_at();

-- ---------------------------------------------------------------------------
-- RLS: anon/authenticated read the collection definitions and ONLY published
-- items. Writes & draft reads go through service_role (bypasses RLS).
-- ---------------------------------------------------------------------------
alter table public.ek_collections enable row level security;
alter table public.ek_collection_items enable row level security;

grant select on public.ek_collections to anon, authenticated;
grant select on public.ek_collection_items to anon, authenticated;

grant all on public.ek_collections to service_role;
grant all on public.ek_collection_items to service_role;

drop policy if exists "ek public reads collections" on public.ek_collections;
create policy "ek public reads collections"
  on public.ek_collections for select
  to anon, authenticated
  using (true);

drop policy if exists "ek public reads published collection items" on public.ek_collection_items;
create policy "ek public reads published collection items"
  on public.ek_collection_items for select
  to anon, authenticated
  using (published_data is not null);
`;
}

/** Eine ek_-Migration: `name` ist der Dateinamens-Suffix ohne Timestamp. */
export interface EkMigration {
  name: string;
  sql: string;
}

/**
 * Alle ek_-Migrationen in Anwendungs-Reihenfolge (init → i18n → globals →
 * symbols → collections). `name` entspricht exakt dem Suffix, den das CLI
 * für die Dateinamen nutzt (`<timestamp>_<name>.sql`) — Konsumenten wie das
 * Studio schreiben ihn 1:1 in `supabase_migrations.schema_migrations`.
 */
export function ekMigrations(options?: { defaultLocale?: string }): EkMigration[] {
  const defaultLocale = options?.defaultLocale ?? DEFAULT_LOCALE;
  return [
    { name: "editkraft_init", sql: initMigration() },
    { name: "editkraft_i18n", sql: i18nMigration(defaultLocale) },
    { name: "editkraft_globals", sql: globalsMigration() },
    { name: "editkraft_symbols", sql: symbolsMigration() },
    { name: "editkraft_collections", sql: collectionsMigration(defaultLocale) },
  ];
}

/** Convenience: die Migrationen mit Default-Locale. */
export const EK_MIGRATIONS = ekMigrations();
